"""Analyst verdicts on crawled candidates (compact; built from crawl signals + brand knowledge).
T = Turkish-connection confidence: H (reliable/official source), M (strong but limited), L (unclear -> manual review).
Merge: alias domains of the same company are listed under `aliases` and are not separate rows."""

# domain: (Company, Country, Industry, T, Turkish evidence, Engage fit H/M/L, note)
V = {
 # ---------------- Germany ----------------
 "bakal.de": ("bakal.de", "Germany", "Food & Beverage", "M", "Self-described 'Türkischer Supermarkt & Lieferservice Hannover'", "H", "Grocery: high repeat"),
 "beslermarkt.de": ("Beslermarkt", "Germany", "Food & Beverage", "M", "Self-described 'authentischer türkischer Supermarkt online'; Turkish-language site", "H", ""),
 "foodpaket.de": ("Foodpaket", "Germany", "Food & Beverage", "M", "Self-described online shop for Turkish groceries; Turkish-language version", "H", ""),
 "hepsi-markt.de": ("Hepsi-Markt", "Germany", "Food & Beverage", "M", "Self-described 'Hepsi – Ihr türkischer Supermarkt'; Turkish-language site", "H", ""),
 "morgenmarkt.de": ("Morgenmarkt", "Germany", "Food & Beverage", "M", "Self-described 'Türkisch orientalischer Online Supermarkt'; Turkish-language site", "H", ""),
 "turkmarketi.de": ("Türkmarketi", "Germany", "Food & Beverage", "M", "Self-described 'Dein türkischer Online-Supermarkt'; Turkish-language site", "H", ""),
 "anteplim.de": ("Anteplim", "Germany", "Food & Beverage", "M", "Authentic Turkish specialities from Antep; Turkish-language storefront", "M", ""),
 "sonmezbaklava.de": ("Sönmez Baklava", "Germany", "Food & Beverage", "M", "Site: 'steht Sönmez Baklava für authentische türkische Baklava'; Turkish-language site", "M", ""),
 "back-lava.de": ("Back-Lava Hamburg", "Germany", "Food & Beverage", "M", "Turkish baklava maker, Turkish-language storefront", "M", ""),
 "hatay.de": ("Hatay Juwelier", "Germany", "Jewelry", "M", "Turkish gold jeweller (Hatay), Turkish-language storefront", "M", ""),
 "evimhome.de": ("Evim Mobilya", "Germany", "Furniture / Home", "M", "Brand 'Evim Mobilya'; Turkish-language storefront, Turkish furniture", "M", ""),
 "naturdeluxe.com": ("Naturdeluxe", "Germany", "Food & Beverage", "M", "Nuts & dried fruit; Turkish-language storefront", "M", ""),
 "semode.de": ("Semode", "Germany", "Fashion / Apparel", "M", "Turkish-language storefront; Turkish fashion", "M", ""),
 "freshnuts.de": ("Fresh Nuts GmbH", "Germany", "Food & Beverage", "M", "Turkish-language site; Turkish nuts & sweets importer-retailer", "M", "Few product links visible"),
 "bakkal.eu": ("Bakkal.eu", "Germany", "Food & Beverage", "M", "Self-described 'Avrupa'nın Türk Marketi' (Europe's Turkish market)", "H", ""),
 # ---------------- Netherlands ----------------
 "yasamfood.com": ("Yasam", "Netherlands", "Food & Beverage", "M", "'Yasam | The Taste of Türkiye'; Turkish-language site", "M", ""),
 "serifoglu.nl": ("Şerifoğlu Baklava", "Netherlands", "Food & Beverage", "M", "Self-described 'Turkse lekkernijspecialist'", "M", ""),
 "olijfoliemarkt.nl": ("Olijfoliemarkt", "Netherlands", "Food & Beverage", "M", "Turkish olive oil (Ayvalık/Edremit) shop with Turkish-language version", "M", ""),
 "elawonen.nl": ("Ela Wonen & Slapen", "Netherlands", "Furniture / Home", "M", "Self-described 'Turkse meubelzaak in Rotterdam'", "M", ""),
 "turkuazmarket.nl": ("Turkuaz Market", "Netherlands", "Food & Beverage", "M", "Turkish grocery webshop (Turkuaz Market)", "H", ""),
 "turkishplaza.com": ("Turkish Plaza", "Netherlands", "Food & Beverage", "M", "'Online Turkish Store in Netherlands'", "H", ""),
 # ---------------- Belgium ----------------
 "bakkalamca.be": ("Bakkal Amca", "Belgium", "Food & Beverage", "M", "'Uw online Turkse supermarkt' / 'Epicerie turque en ligne'", "H", ""),
 "istanbul-market.com": ("Istanbul Market", "Belgium", "Food & Beverage", "M", "Self-described N°1 online grocery for Turkish products; Turkish-language site", "H", ""),
 "dodom.be": ("Dodom", "Belgium", "Food & Beverage", "M", "Brussels online market with Turkish-language storefront", "H", ""),
 # ---------------- France ----------------
 # ---------------- United Kingdom ----------------
 "cafererol.co.uk": ("Cafer Erol London", "United Kingdom", "Food & Beverage", "H", "Cafer Erol: Turkish confectioner founded in Istanbul (1807); UK online shop", "M", ""),
 "ozerlat.co.uk": ("Özerlat UK", "United Kingdom", "Food & Beverage", "H", "UK store of Özerlat, Turkish coffee brand from Istanbul", "M", ""),
 "aytacfood.co.uk": ("Aytac Foods", "United Kingdom", "Food & Beverage", "M", "'Turkish Online Shop & Halal Market'", "H", ""),
 "bakkalim.co.uk": ("Bakkalim", "United Kingdom", "Food & Beverage", "M", "'Turkish Online Food & Grocery Supermarket'", "H", ""),
 "bestgrocery.co.uk": ("Best Grocery", "United Kingdom", "Food & Beverage", "M", "'Turkish Grocery - Online Supermarket'; Turkish-language site", "H", ""),
 "bimarket.co.uk": ("BiMarket", "United Kingdom", "Food & Beverage", "M", "'Turkish & Mediterranean Online Grocery'", "H", ""),
 "bodrumfoods.co.uk": ("Bodrum Foods", "United Kingdom", "Food & Beverage", "M", "Turkish & Mediterranean food online; brand named after Bodrum", "H", ""),
 "bonvila.com": ("Bonvila", "United Kingdom", "Food & Beverage", "M", "'Turkish Supermarket London | 1,500+ products'; Turkish-language site", "H", ""),
 "grocina.com": ("Grocina", "United Kingdom", "Food & Beverage", "M", "'Turkish Market UK'; Turkish-language site", "H", ""),
 "robinfood.co.uk": ("Robin Food", "United Kingdom", "Food & Beverage", "M", "'Robin Food Turkish Supermarket'", "H", ""),
 "turkishonlinemarket.co.uk": ("Turkish Online Market", "United Kingdom", "Food & Beverage", "M", "'Your Turkish online supermarket UK'", "H", ""),
 "turkishpantry.co.uk": ("Turkish Pantry", "United Kingdom", "Food & Beverage", "M", "Turkish pantry products online", "M", ""),
 "anteplie.co.uk": ("Anteplie Bakerie & Baklava", "United Kingdom", "Food & Beverage", "M", "Antep-style baklava bakery (Anteplie = 'from Antep')", "M", ""),
 "baklavaciuk.com": ("Baklavaci Birmingham", "United Kingdom", "Food & Beverage", "M", "Authentic handmade Turkish baklava", "M", ""),
 "merhababoutique.com": ("Merhaba Boutique", "United Kingdom", "Fashion / Apparel", "M", "Turkish-language storefront, Turkish fashion", "M", ""),
 "turksarayi.com": ("Türk Sarayı", "United Kingdom", "Fashion / Apparel", "M", "'Turkish Clothing Shops in London'", "M", ""),
 "oncuhome.co.uk": ("Öncü Home", "United Kingdom", "Furniture / Home", "M", "Turkish cookware/tableware retailer (Öncü)", "M", ""),
 "sofaturkey.com": ("SofaTurkey", "United Kingdom", "Furniture / Home", "M", "'Buy Turkish sofas, corner sets'", "L", ""),
 "mughegourmet.com": ("Mughe Gourmet", "United Kingdom", "Food & Beverage", "M", "Authentic baklava, lokum, Turkish sweets", "M", ""),
 # ---------------- round 2-4 additions ----------------
 "cici-home.com": ("CiCi HOME", "Germany", "Furniture / Home", "M", "Home & kitchen shop specialised in Turkish tea/coffee ware (dedicated Türkischer Tee / Türkischer Kaffee categories)", "H", ""),
 "turkishhome.de": ("Turkish Home", "Germany", "Furniture / Home", "M", "Shop brand 'Turkish Home' selling Turkish homeware brands (Vip Ahmet, Fugurato...)", "M", ""),
 "cilek-moebel.de": ("Yuvam Möbel (Cilek Möbel Europa)", "Germany", "Furniture / Home", "M", "Official European partner of Çilek (Turkish kids' furniture brand); imprint Bekir Öncü", "M", ""),
 "capadocia.de": ("Capadocia Kuruyemiş", "Germany", "Food & Beverage", "M", "'Capadocia Kuruyemiş' nuts & dried fruit; Turkish-language storefront", "H", ""),
 "tazecik.de": ("Tazecik", "Germany", "Food & Beverage", "M", "Turkish-language shop for organic regional Turkish products ('Yöresel Ürünler')", "H", ""),
 "tryaladdin.com": ("Aladdin", "Germany", "Food & Beverage", "M", "'Authentische türkische Produkte einkaufen'", "H", ""),
 "kochdichturkisch.de": ("KochDichTürkisch", "Germany", "Food & Beverage", "M", "Turkish cooking brand (books, courses) with shop for Turkish olive oil, rakı, bulgur", "M", ""),
 "bellaneva.com": ("Bellaneva", "Germany", "Fashion / Apparel", "M", "Hijab fashion shop with Turkish-language storefront", "M", ""),
 "alyadress.de": ("Alya Dress", "Germany", "Fashion / Apparel", "M", "Hijab evening wear shop with Turkish-language storefront", "M", ""),
 "istikbalnrw.com": ("İstikbal NRW", "Germany", "Furniture / Home", "M", "Regional dealer of Turkish brand İstikbal (Köln/Dortmund/Duisburg); Turkish-language site", "M", ""),
 "bellonanrw.de": ("Bellona NRW Möbel", "Germany", "Furniture / Home", "M", "Köln dealer of Turkish furniture brand Bellona", "L", ""),
 "bellonadeutschland.de": ("Bellona Möbelhaus Stuttgart", "Germany", "Furniture / Home", "M", "Stuttgart store of Turkish furniture brand Bellona", "L", ""),
 "akaslanmobilya.de": ("Akaslan Mobilya", "Germany", "Furniture / Home", "M", "'Akaslan Mobilya' furniture house in Köln (Turkish-language brand name + Turkish furniture)", "L", ""),
 "anamarket.nl": ("Ana Market", "Netherlands", "Food & Beverage", "M", "'Turks-Oosterse supermarkt in Enschede' with online ordering", "H", ""),
 "bazaaro.nl": ("Bazaaro", "Netherlands", "Food & Beverage", "M", "Grocery webshop with Turkish bakery/pudding categories (Turkse bakproducten)", "H", ""),
 "ekselansonline.com": ("Ekselans Online", "Netherlands", "Furniture / Home", "M", "Dutch homeware shop focused on Turkish coffee/tea ware", "M", ""),
 "karakushome.com": ("Karakus Home", "Netherlands", "Furniture / Home", "M", "'The webshop for Turkish gifts', part of Güven group", "M", ""),
 "limanonline.com": ("LimanOnline (Liman Home)", "Netherlands", "Furniture / Home", "M", "Dutch homeware webshop with Turkish-language version, Turkish brands (Karaca, Paşabahçe)", "H", ""),
 "gulcanhome.eu": ("Gulcan Home", "Netherlands", "Furniture / Home", "M", "Self-described 'Turkse huishoudwinkel' (Karaca, Paşabahçe)", "H", "Karaca.nl appears to be run by same ecosystem - not merged"),
 "turkse-artikelen.nl": ("Soner Turkse Artikelen", "Netherlands", "Consumer Goods", "M", "'Soner-Turkse Artikelen' webshop", "M", ""),
 "ihlas.be": ("IHLAS Mobilia Gent", "Belgium", "Furniture / Home", "M", "Furniture store Gent with Turkish-language site", "L", ""),
 "deliceland.com": ("Délice Land", "France", "Food & Beverage", "M", "Loukoum & baklava shop (Strasbourg) with Turkish-language storefront", "M", ""),
 "istanbul-meuble.fr": ("Istanbul Meuble", "France", "Furniture / Home", "M", "'Istanbul Meuble' furniture boutique, Turkish furniture", "L", ""),
 "mobilyum.co.uk": ("Mobilyum Furniture", "United Kingdom", "Furniture / Home", "M", "'Chic, contemporary Turkish furniture' (Mobilyum = Turkish for 'my furniture')", "L", ""),
 "caramelpatisserie.co.uk": ("Caramel Patisserie", "United Kingdom", "Food & Beverage", "M", "'Turkish desserts, baklava' patisserie with online shop", "M", ""),
 "gultekinbakery.co.uk": ("Gultekin Bakery", "United Kingdom", "Food & Beverage", "M", "'Traditional Turkish Bakery'", "M", ""),
 "acaciafurniture.uk": ("Acacia Furniture", "United Kingdom", "Furniture / Home", "M", "Self-described 'Turkish furniture shop'", "L", ""),
 "evim.ch": ("Evim", "Switzerland", "Furniture / Home", "M", "Turkish home & kitchen shop (Çaykur, Hatır); imprint Geschäftsführer Ibrahim Akyol", "H", "Outside priority countries"),
 "bizimkiler.ch": ("Bizimkiler", "Switzerland", "Food & Beverage", "M", "Self-described 'Türkischer Online-Shop in der Schweiz'", "H", "Outside priority countries"),
 "turkishmarket.ch": ("Turkish Market CH", "Switzerland", "Food & Beverage", "M", "Turkish grocery & butcher online (TR/EN site)", "H", "Outside priority countries"),
 "b11.com.tr": ("B11 Furniture", "Turkey / Europe", "Furniture / Home", "M", "'Turkish Furniture in Europe' - Turkish maker selling online into Europe", "L", "Turkey-based; EU entity not confirmed"),
 "samafoods.co.uk": ("Sama Foods", "United Kingdom", "Food & Beverage", "M", "'Turkish Online Food & Grocery Supermarket UK'", "H", ""),
 "goturkishfood.com": ("Go Turkish Food", "United Kingdom", "Food & Beverage", "M", "Turkish food webshop (GoTurkishFood), GBP pricing", "H", ""),
 "hepsikapinda-shop.com": ("Hepsi Kapında", "Germany", "Food & Beverage", "M", "Turkish-named grocery webshop ('Hepsi Kapında' = all at your door) with Turkish-language version, Turkish brands", "H", ""),
 "edensmarket.be": ("Eden's Market", "Belgium", "Food & Beverage", "M", "Grocery webshop with Turkish-language storefront and Turkish sweets range", "H", ""),
 "anthap.co.uk": ("Anthap", "United Kingdom", "Food & Beverage", "M", "Own-label Turkish products (Baharat by Anthap, baklava & Turkish delight, nuts)", "M", ""),
 "zoetterettedelight.com": ("Zoetterette Delight", "Netherlands", "Food & Beverage", "M", "'Turks Fruit Winkel – Turkish Delight: Lokum'; Turkish-language site", "M", ""),
 "ulusoy-export.de": ("Ulusoy Export", "Germany", "Furniture / Home", "M", "Nürnberg carpets & housewares shop; Turkish-language product naming (Osmanlı türk kahve seti)", "M", ""),
}

# alias domains merged into a primary company
ALIASES = {"losyana.nl": "losyana.shop", "losyana.be": "losyana.shop",
           "hijabheela.be": "hijabheela.nl", "slowtide.co.uk": "slowtide.eu", "lcwaikiki.it": "lcwaikiki.de",
           "roastmarket.nl": "roastmarket.de"}

# potentially relevant but Turkish link or EU operation not verified -> needs_manual_review
EXCLUDED_BIG = ["lcwaikiki.de", "mavi.com", "ltbjeans.com", "modanisa.com", "sefamerve.com", "karaca.com.de", "karaca.co.uk", "karaca.fr",
                "karaca.nl", "altinbas.de", "altinbasbijoux.fr", "altinbasjewellery.co.uk", "dogtas.at", "flormar.com", "notecosmetics.com", "istikbaluk.com"]

REVIEW = {
 "hibisway.com": "Loukoum / Turkish coffee brand (France); president Mehdi Rachidi - Turkish ownership not evidenced (product origin only)",
 "sultandelights.co.uk": "Turkish delight seller; founder profile shows no Turkish link (product origin only)",
 "marveli.co.uk": "Turkish delight seller; ownership unverified (product origin only)",
 "luviaolive.co.uk": "Turkish olive oil brand; founder link unverified",
 "thefurniturevilla.co.uk": "Turkish-style furniture; ownership unverified",
 "chateaudemed.co.uk": "Baklava & Turkish delight UK; owner link unverified",
 "sweet-saray.com": "Turkish sweets, USD pricing - EU operation unverified",
 "legacy-living.co.uk": "Turkish sofa collection; owner link unverified",
 "weltew.com": "Turkish furniture, appears Turkey-based",
 "uncafeturc.fr": "Sells Turkish coffee brands; owner link unverified",
 "istanbulfurniture.com": "Turkish furniture; country/entity unverified",
 "katoendraad.nl": "Turkish cotton pestemals; owner link unverified",
 "oleturk.com": "Turkish olive oil, prices in TRY (Turkey-based)",
 "haremlique.com": "Istanbul home-textile brand; EU storefront unverified",
 "modazehrada.com": "Turkey-based hijab evening wear",
 "turkishkosmetik.co.uk": "Turkish cosmetics reseller; owner unverified",
 "alaturca-shop.com": "Turkish-themed home decor; entity unverified",
 "turcamart.com": "Turkish grocery; country unclear (likely US)",
 "sabahbedding.com": "Turkish bedding brand; B2B hotel focus",
 "moebel-welt.com": "Cem Welt Möbel GmbH Berlin; Turkish link by name only",
 "uzunmoebel.shop": "Turkish link by name only",
 "mozaiekbaklava.nl": "Baklava shop; owner link unverified",
 "sefahuyukjewels.co.uk": "Jewellery; Turkish link unverified",
 "meyno.fr": "Halal supermarket Strasbourg; Turkish link weak",
 "menkos.de": "Sells Turkish cosmetics/kolonya; owner Turkish link not verified",
 "bazaarica.com": "Turkish cosmetics retailer; ownership/EU entity not verified",
 "alimhome.de": "Home textiles, Turkish link weak",
 "ersinmoebel.de": "Berlin furniture store surfaced for 'türkische Möbel'; no explicit Turkish statement",
 "hamamista.com": "Hamam towels; ownership not verified",
 "josefsbio.de": "Bio sucuk; Turkish link unclear",
 "koytad.de": "KÖYTAD halal frozen food; may be B2B wholesale",
 "taguja.com": "Spices & Turkish specialities; ownership unclear",
 "hira-moda.de": "Modest fashion; Turkish link not stated",
 "juwelier-anadolu.nl": "Name suggests Anatolian origin only",
 "hobokenmarket.be": "Ethnic market webshop; Turkish link weak",
 "dudemsashop.be": "Grocery webshop; Turkish link weak",
 "altinbasjuwelier.nl": "Name matches Altınbaş but relation to Altınbaş brand unverified",
 "koton.com": "Istanbul fashion brand; no EU storefront detected (TR-only site)",
 "kigili.com": "Turkish menswear; en storefront only, EU shipping not verified",
 "tugba.com": "Turkish modest-fashion brand; EU storefront not verified",
 "englishhome.com": "Turkish home brand; EU storefront not verified",
 "madamecoco.com": "Turkish home brand; TR-only site",
 "hafizmustafa.com": "Istanbul confectioner; international shipping, EU entity unverified",
 "mehmetefendi.com": "Turkish coffee brand; direct EU webshop unverified",
 "penti.com": "Turkish lingerie brand; ships to Romania only (EU) - outside target countries",
 "grandturkishbazaar.com": "Turkey-based cross-border store; no EU entity",
 "turkishsouq.com": "Turkey-based cross-border store; no EU entity",
 "turkishtaste.com": "Ships from Turkey; no EU entity",
 "turkishgiftbuy.com": "Ships from Turkey; no EU entity",
 "foodturkiye.com": "Ships from Turkey; no EU entity",
 "londongrocery.net": "Turkish grocery but many wholesale signals",
 "galaximart.co.uk": "Turkish sofas mention only",
 "ah-furniture.co.uk": "Turkish furniture mention only",
 "liplips.co.uk": "Handmade Turkish jewellery; owner link not verified",
 "ottomanhands.com": "Turkish-inspired jewellery; owner link not verified",
 "nutz4nuts.co.uk": "Turkish coffee/nuts heavy; ownership unverified",
 "turkishtowelcompany.com": "Turkish towels; company location unverified",
 "jennah-boutique.com": "Modest fashion BE/FR; Turkish link weak",
 "bella-home.com": "Appears in Karaca FR search; relation unverified",
}
